"""Agregar timestamps de trazabilidad a solicitud

Revision ID: 059977ff1e53
Revises: 67c7a28c08a3
Create Date: 2026-06-10 20:30:44.317462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059977ff1e53'
down_revision: Union[str, Sequence[str], None] = '67c7a28c08a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('fecha_aceptado', sa.DateTime(timezone=True), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_en_camino', sa.DateTime(timezone=True), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_en_sitio', sa.DateTime(timezone=True), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_finalizado', sa.DateTime(timezone=True), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_cancelado', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud', 'fecha_cancelado')
    op.drop_column('solicitud', 'fecha_finalizado')
    op.drop_column('solicitud', 'fecha_en_sitio')
    op.drop_column('solicitud', 'fecha_en_camino')
    op.drop_column('solicitud', 'fecha_aceptado')
    # ### end Alembic commands ###
