"""nombre_de_la_migracion

Revision ID: 5b056f944d8f
Revises: bf69ba935185
Create Date: 2026-04-25 02:50:29.814860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b056f944d8f'
down_revision: Union[str, Sequence[str], None] = 'bf69ba935185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fcm_token')
    # ### end Alembic commands ###
