"""Eliminar tabla cobro_extra

Revision ID: 67c7a28c08a3
Revises: fc52326063dd
Create Date: 2026-06-10 20:05:22.211143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c7a28c08a3'
down_revision: Union[str, Sequence[str], None] = 'fc52326063dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cobro_extra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cobro_extra',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concepto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], name=op.f('cobro_extra_solicitud_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cobro_extra_pkey'))
    )
    # ### end Alembic commands ###
