"""add_puntaje_taller

Revision ID: a50b25f23040
Revises: 059977ff1e53
Create Date: 2026-06-11 12:32:24.815437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50b25f23040'
down_revision: Union[str, Sequence[str], None] = '059977ff1e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taller', sa.Column('puntaje', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taller', 'puntaje')
    # ### end Alembic commands ###
