"""crear tabla taller

Revision ID: bf69ba935185
Revises: bcf8d80cb6d5
Create Date: 2026-04-24 02:38:27.877997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf69ba935185'
down_revision: Union[str, Sequence[str], None] = 'bcf8d80cb6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taller',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('nombre', sa.String(length=100), nullable=False))
    op.add_column('usuario', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('usuario', sa.Column('rol', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'rol')
    op.drop_column('usuario', 'telefono')
    op.drop_column('usuario', 'nombre')
    op.drop_table('taller')
    # ### end Alembic commands ###
