"""mejorar modelo solicitud y cambio de nombre

Revision ID: d68ba367ceda
Revises: 0ec18a249a09
Create Date: 2026-04-26 00:32:56.035307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd68ba367ceda'
down_revision: Union[str, Sequence[str], None] = '0ec18a249a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('urls_fotos', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=True),
    sa.Column('precio_final', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CLASIFICADO', 'PUBLICADO', 'ACEPTADO', 'ASIGNADO', 'EN_CAMINO', 'EN_SITIO', 'FINALIZADO', 'CANCELADO', name='estadosolicitudenum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_servicio.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud')
    # ### end Alembic commands ###
