"""crear_tablas_emergencia_vehicular

Revision ID: e8185a2a21c9
Revises: 0ec18a249a09
Create Date: 2026-06-05 01:50:27.588929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8185a2a21c9'
down_revision: Union[str, Sequence[str], None] = '0ec18a249a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_servicio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('palabras_clave', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mecanico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mecanico_especialidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('urls_fotos', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=True),
    sa.Column('precio_final', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CLASIFICADO', 'PUBLICADO', 'ACEPTADO', 'ASIGNADO', 'EN_CAMINO', 'EN_SITIO', 'FINALIZADO', 'CANCELADO', name='estadosolicitudenum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipo_servicio.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion_auxilio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanico.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('QR', 'TARJETA', 'EFECTIVO', name='metodopagoenum'), nullable=False),
    sa.Column('estado_pago', sa.Enum('PENDIENTE', 'COMPLETADO', 'FALLIDO', name='estadopagoenum'), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('asignacion_auxilio')
    op.drop_table('solicitud')
    op.drop_table('mecanico_especialidad')
    op.drop_table('mecanico')
    op.drop_table('notificacion')
    op.drop_table('tipo_servicio')
    # ### end Alembic commands ###
